# firestore_client.py
import os
from dotenv import load_dotenv

load_dotenv()
cred_path = os.getenv('FIRESTORE_CREDENTIALS')  # path to gcloud json
if cred_path:
    os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = cred_path

from google.cloud import firestore

db = firestore.Client()

def add_record_to_firestore(col_name, data: dict):
    # stores metadata as a document
    col = db.collection(col_name)
    doc_ref = col.document()  # autogenerated id
    doc_ref.set(data)
    return doc_ref.id